version: '3.3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-docker-hello-world
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
